project:
  type: website
  output-dir: docs
  render:
    - course_intro.qmd
    - introduction_OS/Gentle_introduction_OS_2024.qmd
    - tools_approaches/Tools_Approaches_OS_2024.qmd
    - data_handling/functions.qmd
    - data_handling/dataHandling.qmd
    - reproducibility/reproducible_docs.qmd
    - reproducibility/reproducible_workflows.qmd
    - reproducibility/exercise_reproducibility.qmd
    - reproducibility/intro-reproducible-environment.qmd
    - systematic_reviews/Systematic_Reviews.qmd
    - systematic_reviews/meta_analysis.qmd
    


format:
  revealjs:
      highlight-style: a11y
      theme: simple
      code-link: true

execute:
  freeze: auto

website:
    favicon: figures/favicon.ico
